# Generated by Django 4.0.3 on 2022-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='查询条件')),
                ('objs', models.ManyToManyField(blank=True, to='dashboard.order')),
            ],
            options={
                'verbose_name': '搜索记录',
            },
        ),
    ]
